export default {
    products: [
        {
            inventory: 0,
            image: "thong-minh.png",
            name: "truong",
            slug: "10",
            id: 1,
            rating: [3],
            price: 29998,
            description: "hang ra to khong co gi de che",
        },
        {
            inventory: 2,
            image: "thong-minh.png",
            name: "truong",
            slug: "11",
            id: 2,
            rating: [3],
            price: 29998,
            description: "hang ra to khong co gi de che",
        },
        {
            inventory: 0,
            image: "thong-minh.png",
            name: "truong",
            slug: "12",
            id: 3,
            rating: [3],
            price: 29998,
            description: "hang ra to khong co gi de che",
        },
        {
            inventory: 0,
            image: "thong-minh.png",
            name: "truong",
            slug: "13",
            id: 4,
            rating: [3],
            price: 29998,
            description: "hang ra to khong co gi de che",
        },
        {
            inventory: 0,
            image: "thong-minh.png",
            name: "truong",
            slug: "14",
            id: 5,
            rating: [3],
            price: 29998,
            description: "hang ra to khong co gi de che",
        },
    ],
    carts: [
        {
            itemId: 1,
            name: "product 1",
            image: "thong-minh.png",
            price: 29998,
            qty: 12,
        },
        {
            itemId: 2,
            name: "product 2",
            image: "thong-minh.png",
            price: 29998,
            qty: 12,
        },
        {
            itemId: 3,
            name: "product 3",
            image: "thong-minh.png",
            price: 29998,
            qty: 12,
        },
    ],
    count: 2,
    isLogin: false,
    snackbar: {
        show: false,
        text: "truong",
        color: "red",

    },
    isCart: 2,
    subTotal: 200000,
    cartTotal: '12',
    tax:120000,
    grandTotal:130000,
    first_name: 'nguyen',
    last_name: 'dinh',
    address: 'vp',
    city: 'vp',
    state: 'vp',
    zipcode: 12213,
    phone: 1,
    email:'dinhsdf@fas.com'
};
